export function drawPDFFooter(doc, pageNumber) {

    doc.setTextColor(120);

    doc.setFontSize(10);

    doc.text(
        "Generated by Fezher Supreme ERP",
        14,
        290
    );

    doc.text(
        `Page ${pageNumber}`,
        195,
        290,
        { align: "right" }
    );

}