import { serve } from "https://deno.land/std@0.224.0/http/server.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
  "Content-Type": "application/json",
};

serve(async (req) => {
  // Handle browser CORS preflight request
  if (req.method === "OPTIONS") {
    return new Response("ok", {
      status: 200,
      headers: corsHeaders,
    });
  }

  if (req.method !== "POST") {
    return new Response(
      JSON.stringify({
        success: false,
        error: "Method not allowed",
      }),
      {
        status: 405,
        headers: corsHeaders,
      }
    );
  }

  try {
    const body = await req.json();

    const {
      to,
      subject,
      message,
      format,
      dashboard,
    } = body;

    console.log("========== SEND EMAIL REPORT ==========");
    console.log("Recipient:", to);
    console.log("Subject:", subject);
    console.log("Format:", format);
    console.log("=======================================");

    // Validate recipient
    if (!to) {
      return new Response(
        JSON.stringify({
          success: false,
          error: "Recipient email address is required",
        }),
        {
          status: 400,
          headers: corsHeaders,
        }
      );
    }

    // Validate email format
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

    if (!emailRegex.test(to)) {
      return new Response(
        JSON.stringify({
          success: false,
          error: "Invalid recipient email address",
        }),
        {
          status: 400,
          headers: corsHeaders,
        }
      );
    }

    // Resend API key must be stored as a Supabase secret.
    const resendApiKey = Deno.env.get("RESEND_API_KEY");

    if (!resendApiKey) {
      console.error("RESEND_API_KEY is not configured");

      return new Response(
        JSON.stringify({
          success: false,
          error: "Email service is not configured",
        }),
        {
          status: 500,
          headers: corsHeaders,
        }
      );
    }

    const fromEmail =
      Deno.env.get("EMAIL_FROM") || "Fezher Supreme <onboarding@resend.dev>";

    const reportFormat = String(format || "pdf").toUpperCase();

    const reportHtml = `
      <div style="font-family: Arial, sans-serif; max-width: 700px; margin: auto;">
        <h2>Fezher Supreme Executive Report</h2>

        <p>${escapeHtml(
          message || "Please find the executive report attached."
        )}</p>

        <hr />

        <h3>Executive Summary</h3>

        <table style="border-collapse: collapse; width: 100%;">
          <tr>
            <td style="padding: 8px; border: 1px solid #ddd;">
              Revenue
            </td>
            <td style="padding: 8px; border: 1px solid #ddd;">
              ${dashboard?.businessHealth?.revenue ?? 0}
            </td>
          </tr>

          <tr>
            <td style="padding: 8px; border: 1px solid #ddd;">
              Expenses
            </td>
            <td style="padding: 8px; border: 1px solid #ddd;">
              ${dashboard?.businessHealth?.expenses ?? 0}
            </td>
          </tr>

          <tr>
            <td style="padding: 8px; border: 1px solid #ddd;">
              Profit
            </td>
            <td style="padding: 8px; border: 1px solid #ddd;">
              ${dashboard?.businessHealth?.profit ?? 0}
            </td>
          </tr>

          <tr>
            <td style="padding: 8px; border: 1px solid #ddd;">
              Sales
            </td>
            <td style="padding: 8px; border: 1px solid #ddd;">
              ${dashboard?.businessHealth?.sales ?? 0}
            </td>
          </tr>
        </table>

        <p style="margin-top: 24px; color: #666;">
          Report format requested: ${reportFormat}
        </p>

        <p style="color: #666;">
          Generated by Fezher Supreme.
        </p>
      </div>
    `;

    // Send email through Resend
    const resendResponse = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${resendApiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        from: fromEmail,
        to: [to],
        subject:
          subject || "Executive Report - Fezher Supreme",
        html: reportHtml,
      }),
    });

    const resendData = await resendResponse.json();

    if (!resendResponse.ok) {
      console.error("Resend error:", resendData);

      return new Response(
        JSON.stringify({
          success: false,
          error: "Email provider rejected the request",
          details: resendData,
        }),
        {
          status: 502,
          headers: corsHeaders,
        }
      );
    }

    console.log("Email sent successfully:", resendData);

    return new Response(
      JSON.stringify({
        success: true,
        message: "Report email sent successfully",
        emailId: resendData.id,
      }),
      {
        status: 200,
        headers: corsHeaders,
      }
    );
  } catch (error) {
    console.error("Send email error:", error);

    return new Response(
      JSON.stringify({
        success: false,
        error: error instanceof Error
          ? error.message
          : "Unknown email sending error",
      }),
      {
        status: 500,
        headers: corsHeaders,
      }
    );
  }
});

function escapeHtml(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}